steps:
- name: node:14-alpine
  entrypoint: npm
  args: ['install']

- name: node:14-alpine
  entrypoint: npm
  args: ['run', 'lint']

- name: node:14-alpine
  entrypoint: npm
  args: ['run', 'test:coverage']

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:326.0.0
  entrypoint: gcloud
  args:
  - builds
  - submit
  - --tag=gcr.io/${_GCP_PROJECT}/wizekit-slack-app:${SHORT_SHA}

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:326.0.0
  entrypoint: gcloud
  args:
  - run
  - deploy
  - wizekit-slack-app-cloudrun
  - --image=gcr.io/${_GCP_PROJECT}/wizekit-slack-app:${SHORT_SHA}
  - --platform=managed
  - --region=us-east1
  - --project=${_GCP_PROJECT}
  - --allow-unauthenticated
  - --service-account=${_GCP_SERVICE_ACCOUNT}
  - >
    --set-env-vars=
    SLACK_TOKEN=${_SLACK_TOKEN},
    COMMIT_SHA=${COMMIT_SHA},
    GOOGLE_OAUTH_CLIENT_SECRET=${_GOOGLE_OAUTH_CLIENT_SECRET},
    GOOGLE_OAUTH_HOSTED_DOMAIN=${_GOOGLE_OAUTH_HOSTED_DOMAIN}
